DROP TABLE IF EXISTS INVENTORY;
DROP TABLE IF EXISTS DELIVERY;
DROP TABLE IF EXISTS PRODUCTS;
DROP TABLE IF EXISTS DEPARTMENT;

CREATE TABLE DEPARTMENT(
DEPT_NUM NUMERIC(2) PRIMARY KEY,
DEPT_NAME VARCHAR(30) NOT NULL
);

CREATE TABLE PRODUCTS(
SKU NUMERIC(8) PRIMARY KEY,
PROD_NAME VARCHAR(30) NOT NULL,
BRAND VARCHAR(30) NOT NULL,
DEPT_NUM NUMERIC(2) REFERENCES DEPARTMENT,
UNIT_PRC NUMERIC(5,2)
);

CREATE TABLE DELIVERY(
DEL_NUM NUMERIC(8) PRIMARY KEY,
DATE_REC DATETIME
);

CREATE TABLE INVENTORY(
SKU NUMERIC(8),
DEL_NUM NUMERIC(8),
EXPIR_DATE DATE,
QUANTITY NUMERIC(8),
primary key (SKU, DEL_NUM, EXPIR_DATE)
);
